package com.hackday.fk.groceryv2.models;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;



/**
 * Created by siba.sethy on 23/06/17.
 */
@Entity
@Table(name = "ingredients")
public class Ingredients {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's email

    @NotNull
    private String name;

    @NotNull
    private String description;

    @NotNull
    private float price;

    public long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String desc) {
        this.description = desc;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }


    public Ingredients(){
    }

    public Ingredients(long id){
        this.id=id;

    }

    public Ingredients(String name, String desc, float price)
    {
        this.name=name;
        this.description=desc;
        this.price=price;
    }



}


