package com.hackday.fk.groceryv2.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by siba.sethy on 23/06/17.
 */
@Entity
@Table(name = "inventory")
public class Inventory {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // The user's email

    @NotNull
    private String name;

    @NotNull
    private Float price;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Integer getRecommendedQTY() {
        return recommendedQTY;
    }

    public void setRecommendedQTY(Integer recommendedQTY) {
        this.recommendedQTY = recommendedQTY;
    }

    public Integer getInstockQTY() {
        return instockQTY;
    }

    public void setInstockQTY(Integer instockQTY) {
        this.instockQTY = instockQTY;
    }

    public Long getResturantID() {
        return resturantID;
    }

    public void setResturantID(Long resturantID) {
        this.resturantID = resturantID;
    }

    @NotNull
    private Integer recommendedQTY;

    @NotNull
    private Integer instockQTY;

    @NotNull
    private Long resturantID;

    public Inventory(){}
    public Inventory(Long id)
    {
        this.id=id;
    }
    public Inventory(Long resturantID, String name, Float price, Integer recommendedQTY, Integer instockQTY )
    {
        this.resturantID=resturantID;
        this.name=name;
        this.price=price;
        this.resturantID=resturantID;
        this.instockQTY=instockQTY;
    }
}
